name: Feature request
description: Suggest a change
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What are you trying to do that gpu-bouncer makes hard?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: What you would like instead
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What you have tried
